# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af416bf36d845a38de57a3f00c6abfcf6fd5690ca8bbebae36edd86c310c79c87b07d7ca4e2b2e9536eab25204beb26ae2f471e79fbb3ddae9a0f40433a3dc74

test:
  secret_key_base: 722328c77ad41b62e57a41fdb1f3cf453c81f2a61c0c60dd4c019fb7072b3331a54cd2917eaa2544fd3e04294c905e5fe23eccbc1ab300a3cb233c157195b4dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
